<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.Horlang\Horizon.HIDL.csproj" />
    <ProjectReference Include="..\Horizon.Rendering\Horizon.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\uix\dead_revolver\Arcade\ArcadeOverlay.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Assets\uix\dead_revolver\Arcade\ArcadeOverlayFrame.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Assets\uix\dead_revolver\Arcade\ArcadeOverlayHighlights.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Assets\uix\dead_revolver\Arcade\ArcadeOverlayShadows.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Assets\uix\dead_revolver\Arcade\BackgroundGrid.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Assets\uix\dead_revolver\*.png;Assets\uix\dead_revolver\*.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\uix\flat\*.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\example\example.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
