<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoCompleteMenu-ScintillaNET" Version="2.1.1" />
    <PackageReference Include="Scintilla5.NET" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.Horlang\Horizon.HIDL.csproj" />
  </ItemGroup>

</Project>